# Generated by Django 3.2.4 on 2021-06-16 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='TaskUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.taskuser'),
            preserve_default=False,
        ),
    ]
